name: NPM publish CD workflow

on:
  release:
    types: [published]

jobs:
  qa:
    uses: morten-olsen/git-law/.github/workflows/qa.yml@main
  build:
    needs: qa
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.release.target_commitish }}
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
        registry-url: https://registry.npmjs.org/
    - run: corepack enable
    - run: yarn install
    - run: git config --global user.name "GitHub CD bot"
    - run: git config --global user.email "github-cd-bot@example.com"
    - run: yarn run build
    # Not supported by yarn 3
    - run: npm version "${{ github.event.release.tag_name }}"
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - run: git push
      env:
        github-token: ${{ secrets.GITHUB_TOKEN }}

